version: '3.8'

services:
  outlook-helper:
    build: .
    container_name: outlook-helper
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=Outlook取件助手
      - APP_PORT=8080
      - APP_ENV=production
      - DB_PATH=./data/outlook_helper.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRE_HOURS=6
      - OUTLOOK_API_BASE_URL=https://your-outlook-api-domain.vercel.app
      - LOG_LEVEL=info
      - LOG_FILE=./logs/app.log
      - CORS_ALLOWED_ORIGINS=*
      - SKIP_EMAIL_VALIDATION=false
      - EMAIL_VALIDATION_WORKERS=5
      - AUTH_TOKEN=your-super-secret-auth-token-change-this
    volumes:
      - outlook_data:/app/data
      - outlook_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  outlook_data:
    driver: local
  outlook_logs:
    driver: local
